# Generated by Django 5.1.2 on 2024-11-11 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=200)),
                ('Usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distribuidor', models.CharField(max_length=200)),
                ('Correo', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('Direccion', models.CharField(max_length=200)),
                ('Usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=200)),
                ('Usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.CharField(max_length=200)),
                ('Cantidad', models.IntegerField(default=0)),
                ('PVenta', models.FloatField(default=0, verbose_name='Precio de Venta')),
                ('PCompra', models.FloatField(default=0, verbose_name='Precio de Compra')),
                ('Descripcion', models.CharField(max_length=1000)),
                ('Imagen', models.ImageField(default='images/default.png', upload_to='images/')),
                ('IdCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.categoria')),
                ('IdDistribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.distribuidor')),
                ('IdMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.marca')),
                ('Usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
