# Generated by Django 5.1.2 on 2024-11-06 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distribuidor', models.CharField(max_length=200)),
                ('Correo', models.CharField(max_length=200)),
                ('Telefono', models.IntegerField(max_length=20)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('Direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.CharField(max_length=200)),
                ('Cantidad', models.IntegerField(default=0)),
                ('PVenta', models.BooleanField(default=0, verbose_name='Precio de Venta')),
                ('PCompra', models.BooleanField(default=0, verbose_name='Precio de Compra')),
                ('Descripcion', models.CharField(max_length=1000)),
                ('IdCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.categorias')),
                ('IdDistribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.distribuidores')),
                ('IdMarcas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.marcas')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
