# Generated by Django 5.1.2 on 2024-11-06 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_categorias_distribuidores_marcas_productos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Distribuidores',
            new_name='Distribuidore',
        ),
        migrations.RenameModel(
            old_name='Marcas',
            new_name='Marca',
        ),
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
