# Generated by Django 5.1.2 on 2024-11-06 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_rename_categorias_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distribuidor', models.CharField(max_length=200)),
                ('Correo', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('Direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='IdDistribuidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.distribuidor'),
        ),
        migrations.DeleteModel(
            name='Distribuidore',
        ),
    ]
