# Generated by Django 5.1.2 on 2024-11-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_distribuidor_alter_producto_iddistribuidor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='IdMarcas',
            new_name='IdMarca',
        ),
    ]
