# Generated by Django 5.1.2 on 2024-11-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_rename_idmarcas_producto_idmarca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='PCompra',
            field=models.FloatField(default=0, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='PVenta',
            field=models.FloatField(default=0, verbose_name='Precio de Venta'),
        ),
    ]
