# Generated by Django 5.1.2 on 2024-11-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='nombre',
        ),
    ]
