# Generated by Django 5.1.2 on 2024-11-09 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0002_rename_first_name_customuser_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='correo',
            new_name='username',
        ),
    ]
